# Generated by Django 5.2.4 on 2025-08-14 08:33

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='أدخل رقم جوال صالح للتواصل والمصادقة', max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='UUID ثابت يُنشئه العميل ويُخزن في localStorage', max_length=36, unique=True, verbose_name='معرّف الجهاز')),
                ('code', models.CharField(default=accounts.models.gen_device_code, help_text='رمز يُرسله المطور للعميل لتفعيل الجهاز', max_length=12, unique=True, verbose_name='رمز التفعيل')),
                ('is_active', models.BooleanField(default=False, help_text='يشير إذا كان هذا الجهاز مفعلًا حالياً', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='آخر استخدام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
                'ordering': ['-last_used'],
            },
        ),
    ]
