services:
  - type: web
    name: quiz-pwa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python - << 'PYCODE'
from django.contrib.auth import get_user_model
User = get_user_model()
if not User.objects.filter(username="admin").exists():
    User.objects.create_superuser(
        "admin", "admin@example.com", "StrongP@ssw0rd"
    )
PYCODE
      && gunicorn quiz_project.wsgi:application

    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        value: "b06aa0d36bfd9e1f1e7c039d37e6fc28"
      - key: ALLOWED_HOSTS
        value: "myrepo-28.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://myrepo-28.onrender.com,https://localhost,https://127.0.0.1"
      - key: USE_REMOTE_DB
        value: "True"
      - key: DB_NAME
        value: "quizdb_48zp"
      - key: DB_USER
        value: "quizdb_48zp_user"
      - key: DB_PASSWORD
        value: "HSnoVUJu1bEp0qQVFAeCshxXcD8QHUFy"
      - key: DB_HOST_EXTERNAL
        value: "dpg-d18ld78gjchc73996mpg-a.oregon-postgres.render.com"
      - key: DB_PORT
        value: "5432"
