services:
  - type: static
    name: quiz_frontend
    env: node
    region: nrt
    plan: free
    root: frontend/vue-quiz
    buildCommand: |
      set -e
      npm ci
      npm run build
    publish: dist

  - type: web
    name: quiz_backend
    env: python
    branch: main
    region: nrt
    plan: free
    root: backend

    buildCommand: |
      set -e
      pip install --upgrade pip setuptools
      pip install -r requirements.txt
      python manage.py collectstatic --no-input

    startCommand: |
      set -e
      python manage.py migrate --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; User=get_user_model(); \
if not User.objects.filter(username='admin').exists(): \
    User.objects.create_superuser('admin','admin@example.com','admin')"
      gunicorn quiz_project.wsgi:application --bind 0.0.0.0:${PORT}

    envVars:
      - key: DJANGO_SECRET_KEY
        value: YOUR_SECRET_KEY
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "myrepo-29.onrender.com"
      - key: DB_NAME
        value: quizdb1_li31
      - key: DB_USER
        value: quizdb1_li31_user
      - key: DB_PASSWORD
        value: uYMGKY953sG7jQhfJGsAYS3yDpmOJwS7
      - key: DB_HOST
        value: dpg-d1voaker433s73fsuk00-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
