services:
  - type: web
    name: myrepo-29                # اسم الخدمة في لوحة تحكم Render
    env: python                    # البيئة: Python (Django)

    buildCommand: |               # أوامر البناء تُنفّذ خطوة خطوة
      # 1) الانتقال إلى مجلد الواجهة الأمامية
      cd frontend/quiz-frontend

      # 2) تثبيت الحزم وبناء الواجهة
      npm ci                        # يقرأ package-lock.json ويثبت
      npm run build                # يولّد مجلد dist

      # 3) العودة إلى مجلد backend
      cd ../../backend

      # 4) تثبيت متطلبات Python
      pip install --upgrade pip setuptools
      pip install -r requirements.txt

      # 5) جمع كل الملفات الثابتة (Django + مجلد dist)
      python manage.py collectstatic --no-input

    startCommand: |               # أمر تشغيل الخدمة
      # ترحيل قواعد البيانات إن وجدت
      python manage.py migrate --noinput && \
      # إطلاق واجهة WSGI عبر Gunicorn
      gunicorn quiz_project.wsgi:application \
        --bind 0.0.0.0:$PORT \
        --workers=3 \
        --log-level=info

    
    envVars:
      - key: DJANGO_SECRET_KEY
        value: b06aa0d36bfd9e1f1e7c039d37e6fc28
      - key: DJANGO_DEBUG
        value: true
      - key: USE_REMOTE_DB
        value: true
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,myrepo-29.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:8080,https://myrepo-29.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://myrepo-29.onrender.com
      - key: DB_NAME
        value: quizdb1_li31
      - key: DB_USER
        value: quizdb1_li31_user
      - key: DB_PASSWORD
        value: uYMGKY953sG7jQhfJGsAYS3yDpmOJwS7
      - key: DB_HOST_EXTERNAL
        value: dpg-d1voaker433s73fsuk00-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432