services:
  - type: web
    name: vue-django-app
    env: python
    buildCommand: |
      # 1. بناء الواجهة الأمامية Vue
      cd frontend
      npm install
      npm run build

      # 2. نسخ ملفات Vue المبنية إلى مكان يستطيع Django قراءته
      cp -r dist ../backend/frontend_build/dist

      # 3. العودة إلى مجلد Django لتثبيت الحزم
      cd ../backend
      pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11