# render.yaml

services:
  - type: web
    name: quiz_project
    env: python
    rootDirectory: backend  # لأن manage.py موجود هنا

    buildCommand: |
      # 1. بناء React
      cd ../frontend/quiz-frontend
      npm install
      npm run build
      
      # 2. إعداد Django
      cd ../../backend
      pip install --upgrade setuptools
      pip install -r requirements.txt
      python manage.py collectstatic --no-input

    startCommand: |
      # 1. عمل migrate
      python manage.py migrate --noinput

      # 2. إنشاء superuser إن لم يكن موجودًا
      python - << 'PYCODE'
from django.contrib.auth import get_user_model
User = get_user_model()
if not User.objects.filter(username="admin").exists():
    User.objects.create_superuser(
        username="admin",
        email="admin@example.com",
        password="admin"
    )
PYCODE

      # 3. تشغيل السيرفر
      gunicorn quiz_project.wsgi:application --bind 0.0.0.0:$PORT --log-file -

    envVars:
      - key: DJANGO_SECRET_KEY
        value: "b06aa0d36bfd9e1e7c039d37e6fc28"

      - key: DJANGO_DEBUG
        value: "False"

      - key: USE_REMOTE_DB
        value: "True"

      - key: ALLOWED_HOSTS
        value: "myrepo-29.onrender.com,localhost,127.0.0.1"

      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:8080,https://myrepo-29.onrender.com"

      - key: CSRF_TRUSTED_ORIGINS
        value: "https://myrepo-29.onrender.com"

      - key: DB_NAME
        value: "quizdb1_li31"

      - key: DB_USER
        value: "quizdb1_li31_user"

      - key: DB_PASSWORD
        value: "uYMGKY953sG7jQhfJGsAYS3yDpmOJwS7"

      - key: DB_HOST
        value: "dpg-d1voaker433s73fsuk00-a.oregon-postgres.render.com"

      - key: DB_PORT
        value: "5432"