services:
  - type: web
    name: myrepo-29
    env: python
    plan: free
    rootDir: backend  # هذا مهم جداً لتحديد مجلد Django

    buildCommand: |
      # 1) بناء React
      cd ../frontend/quiz-frontend
      npm ci
      npm run build

      # 2) نسخ build إلى Django
      cp -R dist ../../backend/frontend-build

      # 3) إعداد Django
      cd ../../backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --no-input

    startCommand: |               # أمر بدء الخدمة
      # ترحيل الميجريشنات
      python manage.py migrate --noinput && \
      # إطلاق Gunicorn
      exec gunicorn quiz_project.wsgi:application \
        --bind 0.0.0.0:$PORT \
        --workers=3 \
        --log-level=info

    envVars:
      - key: DJANGO_SECRET_KEY
        value: "b06aa0d36bfd9e1f1e7c039d37e6fc28"
      - key: DEBUG
        value: "False"
      - key: USE_REMOTE_DB
        value: true
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,myrepo-29.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:8080,https://myrepo-29.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://myrepo-29.onrender.com
      - key: DB_NAME
        value: quizdb1_li31
      - key: DB_USER
        value: quizdb1_li31_user
      - key: DB_PASSWORD
        value: uYMGKY953sG7jQhfJGsAYS3yDpmOJwS7
      - key: DB_HOST_EXTERNAL
        value: dpg-d1voaker433s73fsuk00-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432