version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: quiz_project.settings
      # SECRET_KEY: ضع هنا مفتاح السر إذا لزم الأمر
      # DATABASE_URL: رابط قاعدة البيانات إن كنت تستخدم خارجية
