# Generated by Django 5.2.4 on 2025-07-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page_number', models.IntegerField()),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('question_ar', models.TextField()),
                ('answer1_en', models.TextField()),
                ('answer1_ar', models.TextField()),
                ('answer2_en', models.TextField()),
                ('answer2_ar', models.TextField()),
                ('answer3_en', models.TextField()),
                ('answer3_ar', models.TextField()),
                ('answer4_en', models.TextField()),
                ('answer4_ar', models.TextField()),
                ('correct_answer', models.IntegerField()),
                ('attached_text', models.TextField(blank=True, null=True)),
                ('attached_text_ar', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
